"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "Kanjis",
      [
        {
          id: "9b7f4e1b-7e63-4cde-bb76-5d4d2c5d7f8b",
          character: "日",
          level: "N5",
          meaning: "Mặt trời, ngày",
          chinaMeaning: "Nhật",
          mnemonic: "Hình tròn của mặt trời",
          kunReading: "ひ, び, か",
          onReading: "ニチ、ジツ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "be9b0d43-3ecb-4b2d-b5f9-5d5c6e4d4f1c",
          character: "月",
          level: "N5",
          meaning: "Mặt trăng, tháng",
          chinaMeaning: "Nguyệt",
          mnemonic: "Hình tròn của mặt trăng",
          kunReading: "つき",
          onReading: "がつ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "f3d9e0d5-6b07-4c8e-a7d2-1e3c63f7d9b6",
          character: "木",
          level: "N5",
          meaning: "Cây",
          chinaMeaning: "Mộc",
          mnemonic: "Cây có nhiều nhánh",
          kunReading: "き",
          onReading: "もく",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "d1e5a1e7-9c9d-4e5b-b8f7-3c74c7b3f84a",
          character: "水",
          level: "N5",
          meaning: "Nước",
          chinaMeaning: "Thủy",
          mnemonic: "Giọt nước",
          kunReading: "みず",
          onReading: "すい",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "644fab29-f13f-4bcd-8d41-fb5ff1e24913",
          character: "絵",
          level: "N5",
          meaning: "Tranh",
          chinaMeaning: "Hội",
          mnemonic: "Bức tranh",
          kunReading: "え",
          onReading: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3g4h5i6j",
          character: "火",
          level: "N5",
          meaning: "Lửa",
          chinaMeaning: "Hỏa",
          mnemonic: "Ngọn lửa bùng cháy",
          kunReading: "ひ",
          onReading: "か",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "2b3c4d5e-6f7a-8b9c-0d1e-2f3g4h5i6j7k",
          character: "犬",
          level: "N5",
          meaning: "Chó",
          chinaMeaning: "Khuyển",
          mnemonic: "Con chó trung thành",
          kunReading: "いぬ",
          onReading: "けん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3c4d5e6f-7a8b-9c0d-1e2f-3g4h5i6j7k8l",
          character: "猫",
          level: "N5",
          meaning: "Mèo",
          chinaMeaning: "Miêu",
          mnemonic: "Mèo kêu meo meo",
          kunReading: "ねこ",
          onReading: "びょう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "4d5e6f7a-8b9c-0d1e-2f3g-4h5i6j7k8l9m",
          character: "山",
          level: "N5",
          meaning: "Núi",
          chinaMeaning: "Sơn",
          mnemonic: "Núi cao vươn lên",
          kunReading: "やま",
          onReading: "さん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "5e6f7a8b-9c0d-1e2f-3g4h-5i6j7k8l9m0n",
          character: "川",
          level: "N5",
          meaning: "Sông",
          chinaMeaning: "Xuyên",
          mnemonic: "Dòng sông chảy",
          kunReading: "かわ",
          onReading: "せん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "6f7a8b9c-0d1e-2f3g-4h5i-6j7k8l9m0n1o",
          character: "田",
          level: "N5",
          meaning: "Ruộng",
          chinaMeaning: "Điền",
          mnemonic: "Ruộng lúa xanh tươi",
          kunReading: "た",
          onReading: "でん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "7a8b9c0d-1e2f-3g4h-5i6j-7k8l9m0n1o2p",
          character: "空",
          level: "N5",
          meaning: "Trời, không gian",
          chinaMeaning: "Không",
          mnemonic: "Bầu trời xanh rộng",
          kunReading: "そら",
          onReading: "くう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "8b9c0d1e-2f3g-4h5i-6j7k-8l9m0n1o2p3q",
          character: "雨",
          level: "N5",
          meaning: "Mưa",
          chinaMeaning: "Vũ",
          mnemonic: "Giọt mưa rơi",
          kunReading: "あめ",
          onReading: "う",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "9c0d1e2f-3g4h-5i6j-7k8l-9m0n1o2p3q4r",
          character: "音",
          level: "N5",
          meaning: "Âm thanh",
          chinaMeaning: "Âm",
          mnemonic: "Âm thanh vang vọng",
          kunReading: "おと",
          onReading: "おん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "0d1e2f3g-4h5i-6j7k-8l9m-0n1o2p3q4r5s",
          character: "光",
          level: "N5",
          meaning: "Ánh sáng",
          chinaMeaning: "Quang",
          mnemonic: "Ánh sáng chiếu rọi",
          kunReading: "ひかり",
          onReading: "こう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "1e2f3g4h-5i6j-7k8l-9m0n-1o2p3q4r5s6t",
          character: "風",
          level: "N5",
          meaning: "Gió",
          chinaMeaning: "Phong",
          mnemonic: "Gió thổi nhẹ nhàng",
          kunReading: "かぜ",
          onReading: "ふう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "2f3g4h5i-6j7k-8l9m-0n1o-2p3q4r5s6t7u",
          character: "雪",
          level: "N5",
          meaning: "Tuyết",
          chinaMeaning: " Tuyết",
          mnemonic: "Bông tuyết trắng xóa",
          kunReading: "ゆき",
          onReading: "せつ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3g4h5i6j-7k8l-9m0n-1o2p-3q4r5s6t7u8v",
          character: "花",
          level: "N5",
          meaning: "Hoa",
          chinaMeaning: "Hoa",
          mnemonic: "Hoa nở rực rỡ",
          kunReading: "はな",
          onReading: "か",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "4h5i6j7k-8l9m-0n1o-2p3q-4r5s6t7u8v9w",
          character: "鳥",
          level: "N5",
          meaning: "Chim",
          chinaMeaning: "Điểu",
          mnemonic: "Chim bay lượn",
          kunReading: "とり",
          onReading: "ちょう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "5i6j7k8l-9m0n-1o2p-3q4r-5s6t7u8v9w0x",
          character: "車",
          level: "N5",
          meaning: "Xe",
          chinaMeaning: "Xa",
          mnemonic: "Xe chạy nhanh",
          kunReading: "くるま",
          onReading: "しゃ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "6j7k8l9m-0n1o-2p3q-4r5s-6t7u8v9w0x1y",
          character: "学校",
          level: "N5",
          meaning: "Trường học",
          chinaMeaning: "Học hiệu",
          mnemonic: "Nơi học tập",
          kunReading: "がっこう",
          onReading: "がっこう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "7k8l9m0n-1o2p-3q4r-5s6t-7u8v9w0x1y2z",
          character: "友",
          level: "N5",
          meaning: "Bạn bè",
          chinaMeaning: "Hữu",
          mnemonic: "Người bạn thân thiết",
          kunReading: "とも",
          onReading: "ゆう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "8l9m0n1o-2p3q-4r5s-6t7u-8v9w0x1y2z3a",
          character: "心",
          level: "N5",
          meaning: "Trái tim, tâm hồn",
          chinaMeaning: "Tâm",
          mnemonic: "Trái tim ấm áp",
          kunReading: "こころ",
          onReading: "しん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
